# Site settings
title: 论文小镇
description: SCI英文论文润色、论文翻译、论文投稿、出国留学 # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
author: Copyright &copy; 2026 - SCI Paper Town
lang: zh_CN

# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: kramdown
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md
